//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.TestService"/> </summary
    public sealed class TestServiceClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public TestServiceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "TestService";
            }
        }
        
        /// <summary>
        /// Call the ServerCall method on the TestService microservice
        /// <see cref="Beamable.Microservices.TestService.ServerCall"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> ServerCall()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<Beamable.Common.Unit>("TestService", "ServerCall", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersTestServiceClient
    {
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForTestServiceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<TestServiceClient>();
        }
        
        public static TestServiceClient TestService(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<TestServiceClient>();
        }
    }
}
