//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.VenlyService.VenlyService"/> </summary
    public sealed class VenlyServiceClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public VenlyServiceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "VenlyService";
            }
        }
        
        /// <summary>
        /// Call the Execute method on the VenlyService microservice
        /// <see cref="Beamable.VenlyService.VenlyService.Execute"/>
        /// </summary>
        public Beamable.Common.Promise<string> Execute(string request)
        {
            object raw_request = request;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("request", raw_request);
            return this.Request<string>("VenlyService", "Execute", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersVenlyServiceClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForVenlyServiceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<VenlyServiceClient>();
        }
        
        public static VenlyServiceClient VenlyService(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<VenlyServiceClient>();
        }
    }
}
